en = open("yoshimitsu_en.json", "r")
ko = open("yoshimitsu_ko.json", "w", encoding="UTF-8")

for line in en:
    if '"Command":' in line:
        new_text = (
            line[19:]
            .replace("in rage ", "레이지 도중 ")
            .replace("(Opponent in front)", "(전방에 상대가 있을 때)")
            .replace("(Opponent behind)", "(후방에 상대가 있을 때)")
            .replace("(Second hit miss)", "(후속타가 헛쳤을 때)")
            .replace("(SSL)", "(시계방향 횡이동)")
            .replace("(SSR)", "(반시계방향 횡이동)")
            .replace("1", "LP")
            .replace("2", "RP")
            .replace("3", "LK")
            .replace("4", "RK")
            .replace("d/b", "1")
            .replace("d/f", "3")
            .replace("u/b", "7")
            .replace("u/f", "9")
            .replace("qcf", "6N23")
            .replace("d", "2")
            .replace("b", "4")
            .replace("f", "6")
            .replace("u", "8")
            .replace("*", "N")
            .replace("j", "홀드")
            .replace("+", "")
            .replace(", ", " ")
            .replace("or", "또는")
            .replace("(to NSS)", "(납도로 전환)")
            .replace("NSS", "납도 중")
            .replace("(to KIN)", "(금타 자세 이행)")
            .replace("KIN", "금타 자세에서")
            .replace("(to MED)", "(무상 자세 이행)")
            .replace("MED", "무상 자세")
            .replace("(to FLE)", "(지뢰인 자세 이행)")
            .replace("FLE", "지뢰인 자세 중")
            .replace("(to WFL)", "(지뢰맹마 이행)")
            .replace("WFL", "지뢰맹마 중")
            .replace("(to IND)", "(만자앉기 자세 이행)")
            .replace("IND", "만자앉기 중")
            .replace("(to INS)", "(만자앉기 자세 이행)")
            .replace("INS", "만자앉기 중")
            .replace("(to DGF)", "(만잠자리 잦세 이행)")
            .replace("DGF", "만잠자리 자세 중")
            .replace("WS", "일어나며 ")
            .replace("BT", "뒤자세")
            .replace("SS", "횡이동 중 ")
            .replace("FC", "앉은 자세에서 ")
            .replace("(Cancel)", "(취소)")
            .replace("D/B", "1")
            .replace("D/F", "3")
            .replace("U/B", "7")
            .replace("U/F", "9")
            .replace("D", "2")
            .replace("B", "4")
            .replace("F", "6")
            .replace("U", "8")
        )
        ko.write(f"{line[:19]}{new_text}")
    else:
        ko.write(line)

en.close()
ko.close()
